site_name: Galasa documentation
site_description: Documentation for the Galasa hybrid software test runner and reporting platform
repo_name: galasa-mkdocs
repo_url: https://github.com/jt-nti/galasa-mkdocs
docs_dir: docs
extra_css:
  - assets/stylesheets/extra.css
theme:
  custom_dir: docs/overrides
  name: material
  logo: assets/galasa-horizontal-white.png
  favicon: assets/galasa-icon-color.png
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  features:
  - content.code.copy
  - navigation.expand
  - navigation.footer
  - navigation.indexes
  - navigation.instant
  # - navigation.sections
  - navigation.tabs
  # - navigation.tabs.sticky
  - navigation.top
  - navigation.tracking
  - toc.follow
  # - toc.integrate
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
plugins:
  - offline
  - search
  - mike
extra:
  version:
    provider: mike
not_in_nav: |
  /home/
nav:
  - index.md
  - About:
    - about/index.md
    - about/different.md
    - about/automation.md
    - about/devops.md
    - about/history.md
  - Docs:
    - docs/index.md
    - Getting started using the Galasa CLI:
      - docs/cli-command-reference/index.md
      - docs/cli-command-reference/cli-prereqs.md
    - Exploring the supplied SimBank tests:
      - docs/running-simbank-tests/index.md
      - docs/running-simbank-tests/simbank-IVT.md
    - Writing your own independent Galasa tests:
      - docs/writing-own-tests/index.md
      - docs/writing-own-tests/writing-test-classes.md
    - The Galasa Ecosystem:
      - docs/ecosystem/index.md
      - docs/ecosystem/ecosystem-architecture.md
    - docs/upgrading.md
    - Managers:
      - docs/managers/index.md
      - CICS TS Managers:
        - docs/managers/cics-ts-managers/index.md
        - docs/managers/cics-ts-managers/cics-ts-ceci-manager.md
        - docs/managers/cics-ts-managers/cics-ts-manager.md
    - Reference:
      - docs/reference/index.md
      - docs/reference/galasa-javadoc.md
  - Releases:
    - releases/index.md
    - releases/license.md
  - Support:
    - support/index.md
  - Community:
    - community/index.md
  - Blogs:
    - hub/index.md
